import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import { buildVapiSystemPrompt, type InterviewPlan } from '@/lib/agent/buildVapiSystemPrompt';
import { checkRateLimit } from '@/lib/rateLimit';

// The Vapi dashboard assistant whose non-model config (voice, transcriber,
// analysis plan, etc.) every temporary per-interview assistant should inherit.
const DASHBOARD_ASSISTANT_ID = '85a73bb3-d87d-4a5a-bd62-55ee094e40eb';

// Hard cost backstop — no round (screening: 4-5 Qs, technical: 6-8 Qs,
// final: 4-6 Qs, plus follow-ups) should ever need this long.
const MAX_DURATION_SECONDS = 1800;

type RoundType = 'screening' | 'technical' | 'final';

function getClientIp(req: NextRequest): string {
  const forwardedFor = req.headers.get('x-forwarded-for');
  return forwardedFor?.split(',')[0]?.trim() || 'unknown';
}

// ─────────────────────────────────────────────
// DYNAMIC KEYTERM EXTRACTION
//
// Deepgram's transcriber mishears domain-specific terms it's never seen
// (e.g. company names, framework/tool names) — Deepgram's keyterm boosting
// (https://developers.deepgram.com/docs/keyterm) primes the transcriber for
// specific vocabulary per-request, up to 500 tokens combined. We build that
// list per-interview from the plan already generated by /api/realtime/initialize
// instead of a static list, and cap well under the limit at MAX_KEYTERMS.
// ─────────────────────────────────────────────
const MAX_KEYTERMS = 100;

// Capitalized words that show up as sentence-initial capitalization in the
// free-text plan fields (gapsToProbe[].gap, strengthsToConfirm) rather than
// as genuine proper nouns — filtered out so they don't waste keyterm slots.
const KEYTERM_STOPWORDS = new Set([
  'the', 'this', 'that', 'these', 'those', 'a', 'an', 'it', 'its', 'they',
  'their', 'he', 'she', 'we', 'candidate', 'has', 'have', 'had', 'is', 'was',
  'were', 'will', 'should', 'could', 'would', 'no', 'not', 'strong', 'weak',
  'good', 'great', 'excellent', 'team', 'role', 'company', 'interview',
  'round', 'but', 'and', 'or', 'for', 'with', 'without', 'despite', 'while',
]);

// Pulls candidate proper nouns (tool/technology/company names) out of a
// free-text sentence — matches runs of consecutive Capitalized/CamelCase
// words (e.g. "Kubernetes", "Google Cloud", "Node.js"), then drops the
// common sentence-starter words a plain regex can't distinguish from real
// proper nouns.
function extractProperNouns(text: string): string[] {
  const matches = text.match(/\b[A-Z][a-zA-Z0-9]*(?:\.[a-zA-Z]+)?(?:\s+[A-Z][a-zA-Z0-9]*)*\b/g) || [];
  return matches
    .map(m => m.trim())
    .filter(m => m.length > 2 && !KEYTERM_STOPWORDS.has(m.toLowerCase()));
}

// skillsToTest entries are already short, structured skill/tech phrases (per
// the initialize prompt) so they're used directly; gapsToProbe/strengthsToConfirm
// are freeform sentences, so proper-noun extraction runs on those instead.
function buildKeyterms(plan: InterviewPlan): string[] {
  const candidates: string[] = [];

  if (plan.company) candidates.push(plan.company);

  for (const area of plan.areas ?? []) {
    for (const skill of area.skillsToTest ?? []) {
      if (skill?.trim()) candidates.push(skill.trim());
    }
  }

  for (const { gap } of plan.gapsToProbe ?? []) {
    if (gap) candidates.push(...extractProperNouns(gap));
  }

  for (const strength of plan.strengthsToConfirm ?? []) {
    if (strength) candidates.push(...extractProperNouns(strength));
  }

  // Dedupe case-insensitively (keep first-seen casing) and cap at the limit.
  const seen = new Set<string>();
  const deduped: string[] = [];
  for (const term of candidates) {
    const key = term.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    deduped.push(term);
    if (deduped.length >= MAX_KEYTERMS) break;
  }
  return deduped;
}

// Module-level cache for the dashboard assistant's non-model config (voice,
// transcriber, analysisPlan, etc.). Measured baseline: this GET costs
// 164-417ms on every single call despite that config almost never changing —
// caching it turns most requests into a single POST. Manual invalidation:
// restart the server (or wait out the TTL) after changing the dashboard
// assistant in the Vapi UI.
let cachedBaseConfig: Record<string, unknown> | null = null;
let cachedAt = 0;
const DASHBOARD_CACHE_TTL_MS = 5 * 60 * 1000;

async function getBaseConfig(privateKey: string): Promise<Record<string, unknown>> {
  const now = Date.now();
  if (cachedBaseConfig && now - cachedAt < DASHBOARD_CACHE_TTL_MS) {
    console.log(`[TIMING] Realtime Start-Call: Using cached dashboard assistant config (age ${now - cachedAt}ms)`);
    return cachedBaseConfig;
  }

  const dashboardRes = await fetch(`https://api.vapi.ai/assistant/${DASHBOARD_ASSISTANT_ID}`, {
    headers: { Authorization: `Bearer ${privateKey}` },
  });

  if (!dashboardRes.ok) {
    const text = await dashboardRes.text();
    console.error('[Vapi] Failed to fetch dashboard assistant:', dashboardRes.status, text);
    throw new Error('Failed to load base assistant config');
  }

  const dashboardAssistant = await dashboardRes.json();

  // Strip identity/timestamp fields (not valid on create) and the fields
  // we're deliberately overriding below; keep everything else (voice,
  // transcriber, analysisPlan, etc.) as-is from the dashboard config.
  const {
    id: _id,
    orgId: _orgId,
    createdAt: _createdAt,
    updatedAt: _updatedAt,
    model: _model,
    firstMessageMode: _firstMessageMode,
    maxDurationSeconds: _maxDurationSeconds,
    isServerUrlSecretSet: _isServerUrlSecretSet,
    ...baseConfig
  } = dashboardAssistant;

  cachedBaseConfig = baseConfig;
  cachedAt = now;
  return baseConfig;
}

export async function POST(req: NextRequest) {
  try {
    const privateKey = process.env.VAPI_PRIVATE_KEY;
    if (!privateKey) {
      return NextResponse.json({ error: 'VAPI_PRIVATE_KEY is not configured' }, { status: 500 });
    }

    // realtime/* routes are intentionally unauthenticated (anonymous users can
    // take a free interview) — auth() here is only to key the rate limiter by
    // account when one exists, falling back to IP for anonymous callers.
    const { userId } = await auth();
    const rateLimitKey = userId ?? `ip:${getClientIp(req)}`;
    if (!checkRateLimit(rateLimitKey)) {
      return NextResponse.json({ error: 'Too many requests' }, { status: 429 });
    }

    const body = await req.json();
    const { plan, roundType } = body as { plan?: InterviewPlan; roundType?: RoundType };

    if (!plan || typeof plan !== 'object' || !Array.isArray(plan.areas) || plan.areas.length === 0) {
      return NextResponse.json({ error: 'plan is required' }, { status: 400 });
    }
    if (roundType !== 'screening' && roundType !== 'technical' && roundType !== 'final') {
      return NextResponse.json({ error: 'roundType must be one of screening, technical, final' }, { status: 400 });
    }

    const t0 = Date.now();
    console.log(`[TIMING] Realtime Start-Call API: Request received at ${t0}`);

    const systemPrompt = buildVapiSystemPrompt(plan, roundType);
    const keyterms = buildKeyterms(plan);
    console.log(`[TIMING] Realtime Start-Call: Extracted ${keyterms.length} keyterms:`, keyterms);

    // Copy the dashboard assistant's non-model config (voice, transcriber,
    // analysis plan, etc.) so behavior doesn't silently change just because
    // the model + first message now come from this route instead. Cached —
    // see getBaseConfig — since this config almost never changes.
    let baseConfig: Record<string, unknown>;
    try {
      baseConfig = await getBaseConfig(privateKey);
    } catch (err: any) {
      return NextResponse.json({ error: err.message || 'Failed to load base assistant config' }, { status: 502 });
    }

    const t1 = Date.now();
    console.log(`[TIMING] Realtime Start-Call: Base config ready at ${t1} (+${t1 - t0}ms)`);

    // Override just transcriber.keyterm with this interview's dynamic list —
    // everything else on transcriber (provider, model, eotThreshold, etc.)
    // stays exactly as inherited from baseConfig.
    const transcriberOverride = keyterms.length > 0
      ? { ...(baseConfig.transcriber as Record<string, unknown> | undefined), keyterm: keyterms }
      : baseConfig.transcriber;

    const createRes = await fetch('https://api.vapi.ai/assistant', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${privateKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        ...baseConfig,
        transcriber: transcriberOverride,
        model: {
          provider: 'openai',
          model: 'gpt-4.1',
          messages: [{ role: 'system', content: systemPrompt }],
          temperature: 0.6,
        },
        firstMessageMode: 'assistant-speaks-first-with-model-generated-message',
        maxDurationSeconds: MAX_DURATION_SECONDS,
      }),
    });

    if (!createRes.ok) {
      const text = await createRes.text();
      console.error('[Vapi] Failed to create temp assistant:', createRes.status, text);
      return NextResponse.json({ error: 'Failed to create interview assistant' }, { status: 502 });
    }

    const created = await createRes.json();
    const t2 = Date.now();
    console.log(`[TIMING] Realtime Start-Call: Created temp assistant ${created.id} at ${t2} (+${t2 - t1}ms)`);

    return NextResponse.json({ assistantId: created.id });
  } catch (err: any) {
    console.error('[Realtime Start-Call Error]', err);
    return NextResponse.json({ error: err.message || 'Failed to start call' }, { status: 500 });
  }
}
